<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Library of interface functions and constants.
 *
 * @package     local_announcements2
 * @copyright   2021 Michael Vangelovski
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

/** Include required files */
require_once($CFG->libdir.'/filelib.php');

/**
 * Serves the plugin attachments.
 *
 * @package  local_announcements
 * @category files
 * @param stdClass $course course object
 * @param stdClass $cm course module object
 * @param stdClass $context context object
 * @param string $filearea file area
 * @param array $args extra arguments
 * @param bool $forcedownload whether or not force download
 * @param array $options additional options affecting the file serving
 * @return bool false if file not found, does not return if found - justsend the file
 */
function local_announcements2_pluginfile($course, $cm, $context, $filearea, $args, $forcedownload, array $options = array()) {
    global $CFG, $DB, $USER;

    if ($context->contextlevel != CONTEXT_SYSTEM) {
        return false;
    }

    $areas = array(
        'attachment' => get_string('postform:areaattachment', 'local_announcements2'),
        'announcement' => get_string('postform:areaannouncement', 'local_announcements2'),
    );

    // filearea must contain a real area
    if (!isset($areas[$filearea])) {
        return false;
    }

    $fs = get_file_storage();
    $relativepath = implode('/', $args);
    $fullpath = "/$context->id/local_announcements2/$filearea/$relativepath";
    if (!$file = $fs->get_file_by_hash(sha1($fullpath)) or $file->is_directory()) {
        return false;
    }

    $forcedownload = true; // download MUST be forced - security!

    $postid = (int)array_shift($args);
    $allowed = announcement::can_user_view_post($postid);
    if (!$allowed) {
        return false;
    }

    // Custom email preview file.
    if (!empty($options['preview'])) {
        if ($options['preview'] === 'email') {
            $imageinfo = $file->get_imageinfo();
            if ($imageinfo['width'] > 660) { // Only do if original > 660px.
                $previewfile = local_announcements_get_email_image_preview($file);
                // replace the file with its preview
                if ($previewfile) {
                    $file = $previewfile;
                    // preview images ignore forced download (they are generated by GD and therefore they are considered reasonably safe).
                    $forcedownload = false;
                }
            }
            // Custom preview has been handled, remove from $options so that send_stored_file does not fail.
            unset($options['preview']); 
        }
    }

    // finally send the file
    send_stored_file($file, 0, 0, $forcedownload, $options);
}
